# Make sure to set the HEROKU_API_KEY environment variable in travis.
# Use heroku authorizations:create to generate a long-term token

services:
  - docker

sudo: false

script:
  - ls
  - heroku container:login
  - heroku container:push web
  - heroku container:release web
