# Make sure to set the HEROKU_API_KEY environment variable in travis.
# Use heroku authorizations:create to generate a long-term token

services:
  - docker

sudo: false

env:
  LOCAL_SITE: poolang.co
  FOREIGN_SITE: php.net

script:
  - heroku container:login
  - heroku container:push web --app poolang
  - heroku container:release web --app poolang
